---

  - name: ARA | Template startup scripts
    template: src="{{role_dir}}/templates/systemd/{{item}}.service.j2" dest="/etc/systemd/system/{{item}}.service" owner="root"
    with_items:
      - "ara-web"
    become: yes

  - name: ARA | Start services
    service: name="{{item}}" state="started" enabled="yes"
    with_items:
      - "ara-web"      
    become: yes
